/*
 * Site language + inline form help for people who are new to Zakat.
 *
 * Every string is written in plain, non-scholarly language and is available
 * in English, Urdu, Hindi and Arabic. The language switcher lives in the app
 * header (and is repeated on the Dashboard and Rates tab) and is independent
 * of the selected currency — picking a currency no longer changes which
 * languages are offered.
 *
 * Usage from ui.js:
 *   ZKHelp.bind(node, key)   — set node text to t(key) and keep it updatable
 *   ZKHelp.refresh()         — re-translate every bound node after setLang()
 *   ZKHelp.t(key)            — one-off translation lookup for chrome text
 *   ZKHelp.availableLangs()  — the site's supported languages
 */
(function (global) {
  "use strict";

  const LANG_LABELS = {
    en: "English",
    ur: "اردو",
    hi: "हिन्दी",
    ar: "العربية",
    bn: "বাংলা",
    id: "Bahasa Indonesia",
    tr: "Türkçe",
    fr: "Français",
  };

  const RTL_LANGS = new Set(["ur", "ar"]);

  const LS_KEY = "zk_help_lang";

  const S = {
    // ---- Shared form intro ----
    intro_zakat: {
      en: "New to Zakat? It is a yearly charity duty: 2.5% of wealth (cash, gold, savings) kept for one lunar year, once it crosses a minimum called nisab. Add each thing this person owns — the app does the maths.",
      ur: "زکوٰۃ ہر سال ادا کی جانے والی فرض خیرات ہے: جو مال (نقدی، سونا، بچت) ایک قمری سال تک آپ کے پاس رہے اور نصاب سے زیادہ ہو، اس کا 2.5%۔ اس شخص کی ہر چیز یہاں درج کریں — حساب ایپ خود کرے گی۔",
      hi: "ज़कात हर साल दी जाने वाली फ़र्ज़ खैरात है: जो माल (नक़दी, सोना, बचत) एक चाँद-साल आपके पास रहे और निसाब से ज़्यादा हो, उसका 2.5%। इस व्यक्ति की हर चीज़ यहाँ जोड़ें — हिसाब ऐप खुद करेगी।",
      ar: "الزكاة صدقة واجبة كل عام: 2.5% من المال (نقود، ذهب، مدّخرات) الذي بقي عندك سنة قمرية وتجاوز النصاب. أضف كل ما يملكه هذا الشخص — والتطبيق يحسب عنك.",
      bn: "যাকাত প্রতি বছর দেওয়া ফরজ দান: যে সম্পদ (নগদ, সোনা, সঞ্চয়) এক চান্দ্র বছর আপনার কাছে থাকে এবং নিসাবের বেশি হয়, তার ২.৫%। এই ব্যক্তির প্রতিটি সম্পদ এখানে যোগ করুন — হিসাব অ্যাপ করবে।",
      id: "Baru mengenal Zakat? Ini kewajiban amal tahunan: 2,5% dari harta (uang, emas, tabungan) yang dimiliki satu tahun lunar dan melebihi nisab. Tambahkan semua yang dimiliki orang ini — aplikasi menghitung sendiri.",
      tr: "Zekâta yeni misiniz? Yıllık bir ibadet: bir kamerî yıl elinizde tuttuğunuz ve nisabı geçen servetinizin (nakit, altın, birikim) %2,5'i. Bu kişiye ait her şeyi girin — hesabı uygulama yapar.",
      fr: "Nouveau à la Zakât ? Aumône annuelle obligatoire : 2,5 % de la richesse (liquidités, or, épargne) détenue une année lunaire dépassant le nisab. Ajoutez tout ce que cette personne possède — l'application calcule.",
    },

    // ---- Member form ----
    member_intro: {
      en: "Zakat is counted per person. Add each family member first, then add what they own.",
      ur: "زکوٰۃ ہر فرد کے حساب سے بنتی ہے۔ پہلے گھر کا ہر فرد شامل کریں، پھر اس کا مال درج کریں۔",
      hi: "ज़कात हर व्यक्ति के हिसाब से बनती है। पहले घर का हर सदस्य जोड़ें, फिर उसका माल दर्ज करें।",
      ar: "تُحسب الزكاة لكل شخص على حدة. أضف أفراد العائلة أولاً، ثم أضف ما يملكون.",
      bn: "যাকাত প্রত্যেক ব্যক্তির জন্য আলাদা হিসাব হয়। আগে পরিবারের সদস্য যোগ করুন, তারপর তার সম্পদ।",
      id: "Zakat dihitung per orang. Tambahkan setiap anggota keluarga terlebih dahulu, lalu tambahkan apa yang mereka miliki.",
      tr: "Zekât kişi başına hesaplanır. Önce her aile üyesini ekleyin, ardından sahip olduklarını girin.",
      fr: "La Zakât est calculée par personne. Ajoutez d'abord chaque membre, puis ce qu'ils possèdent.",
    },
    member_name: {
      en: "Who owns the wealth you are about to add — yourself, your spouse, a parent or a child.",
      ur: "جس کا مال آپ درج کرنے والے ہیں — آپ خود، شریکِ حیات، والدین یا بچے۔",
      hi: "जिसका माल आप जोड़ने जा रहे हैं — आप खुद, जीवनसाथी, माता-पिता या बच्चे।",
      ar: "من يملك هذا المال — أنت، زوجك، أحد الوالدين أو طفل.",
      bn: "যার সম্পদ আপনি যোগ করছেন — আপনি নিজে, স্ত্রী/স্বামী, বাবা-মা বা সন্তান।",
      id: "Siapa pemilik harta yang akan ditambahkan — Anda sendiri, pasangan, orang tua, atau anak.",
      tr: "Ekleyeceğiniz servetin sahibi — kendiniz, eşiniz, ebeveynleriniz veya çocuğunuz.",
      fr: "À qui appartient la richesse que vous allez ajouter — vous-même, votre conjoint(e), un parent ou un enfant.",
    },
    member_rel: {
      en: "How this person is related to the head of the family — Self, Spouse, Son, Daughter, Mother…",
      ur: "گھر کے سربراہ سے رشتہ — خود، شریکِ حیات، بیٹا، بیٹی، والدہ…",
      hi: "घर के मुखिया से रिश्ता — खुद, जीवनसाथी, बेटा, बेटी, माँ…",
      ar: "صلة هذا الشخص برب الأسرة — أنا، زوج، ابن، ابنة، أم…",
      bn: "পরিবারের প্রধানের সাথে সম্পর্ক — নিজে, স্ত্রী/স্বামী, ছেলে, মেয়ে, মা…",
      id: "Hubungan dengan kepala keluarga — Saya, Pasangan, Putra, Putri, Ibu…",
      tr: "Aile reisiyle ilişki — Ben, Eş, Oğul, Kız, Anne…",
      fr: "Le lien avec le chef de famille — Moi, Conjoint(e), Fils, Fille, Mère…",
    },

    // ---- Asset form: fields ----
    asset_category: {
      en: "What kind of wealth is this? Pick the closest match — the form shows only the boxes you need.",
      ur: "یہ کس قسم کا مال ہے؟ قریب ترین قسم چنیں — فارم صرف ضروری خانے دکھائے گا۔",
      hi: "यह किस तरह का माल है? सबसे मिलती-जुलती किस्म चुनें — फ़ॉर्म सिर्फ़ ज़रूरी खाने दिखाएगा।",
      ar: "ما نوع هذا المال؟ اختر الأقرب — وستظهر الحقول اللازمة فقط.",
      bn: "এটি কোন ধরনের সম্পদ? সবচেয়ে কাছাকাছিটি বেছে নিন — ফর্মে শুধু প্রয়োজনীয় ঘরগুলো দেখাবে।",
      id: "Jenis harta apa ini? Pilih yang paling cocok — formulir hanya menampilkan kolom yang diperlukan.",
      tr: "Bu ne tür bir servettir? En uygun olanı seçin — form yalnızca ihtiyacınız olan alanları gösterir.",
      fr: "Quel type de richesse est-ce ? Choisissez la catégorie la plus proche — le formulaire n'affiche que les champs nécessaires.",
    },
    asset_desc: {
      en: "A short name so you can recognise it later — e.g. “HDFC savings” or “Wedding gold chain”.",
      ur: "مختصر نام تاکہ بعد میں پہچان سکیں — جیسے “بینک بچت” یا “شادی کی سونے کی چین”۔",
      hi: "छोटा सा नाम ताकि बाद में पहचान सकें — जैसे “बैंक बचत” या “शादी की सोने की चेन”।",
      ar: "اسم قصير لتعرفه لاحقاً — مثل “حساب التوفير” أو “سلسلة ذهب الزواج”.",
      bn: "ছোট নাম যাতে পরে চিনতে পারেন — যেমন “ব্যাংক সঞ্চয়” বা “বিয়ের সোনার চেন”।",
      id: "Nama singkat agar mudah dikenali — mis. \"Tabungan BCA\" atau \"Kalung emas pernikahan\".",
      tr: "Sonra tanıyabileceğiniz kısa bir ad — örn. \"Ziraat Bankası birikimi\" veya \"Düğün altın kolyesi\".",
      fr: "Un nom court pour le retrouver — ex. \"Livret A\" ou \"Collier en or du mariage\".",
    },
    asset_value: {
      en: "Today's selling value — what you would get if you sold it now, not what you paid for it.",
      ur: "آج کی قیمت — ابھی بیچیں تو جو ملے، وہ لکھیں، خرید قیمت نہیں۔",
      hi: "आज की कीमत — अभी बेचें तो जो मिले, वह लिखें, खरीद कीमत नहीं।",
      ar: "قيمة البيع اليوم — ما تحصل عليه لو بعته الآن، لا ثمن الشراء.",
      bn: "আজকের বিক্রয় মূল্য — এখন বিক্রি করলে যা পাবেন তা লিখুন, কেনার দাম নয়।",
      id: "Nilai jual hari ini — yang akan Anda dapatkan jika dijual sekarang, bukan harga belinya.",
      tr: "Bugünkü satış değeri — şimdi satarsanız elde edeceğiniz, alış fiyatı değil.",
      fr: "Valeur de revente aujourd'hui — ce que vous obtiendriez en le vendant maintenant, pas le prix d'achat.",
    },
    asset_weight: {
      en: "Total weight in grams, from the bill or a jeweller's scale. If you know tola: 1 tola ≈ 11.66 g.",
      ur: "کل وزن گرام میں — بل یا سنار کے تول سے۔ تولہ معلوم ہو تو: 1 تولہ ≈ 11.66 گرام۔",
      hi: "कुल वज़न ग्राम में — बिल या सुनार के तोल से। तोला पता हो तो: 1 तोला ≈ 11.66 ग्राम।",
      ar: "الوزن الكلي بالجرام من الفاتورة أو ميزان الصائغ.",
      bn: "মোট ওজন গ্রামে — রসিদ বা স্বর্ণকারের পাল্লা থেকে। ভরি জানা থাকলে: ১ ভরি ≈ ১১.৬৬ গ্রাম।",
      id: "Total berat dalam gram, dari nota atau timbangan toko emas. Jika tahu mithqal: 1 mithqal ≈ 4,25 g.",
      tr: "Faturadan veya kuyumcu terazisinden gram cinsinden toplam ağırlık. Miskal biliyorsanız: 1 miskal ≈ 4,25 g.",
      fr: "Poids total en grammes, d'après la facture ou la balance d'un bijoutier.",
    },
    asset_purity: {
      en: "The purity stamped on the piece or printed on the bill — most Indian gold jewellery is 22K.",
      ur: "زیور پر مہر یا بل پر لکھی خالصیت — زیادہ تر زیورات 22 کیرٹ کے ہوتے ہیں۔",
      hi: "गहने पर मुहर या बिल पर छपी शुद्धता — ज़्यादातर गहने 22 कैरेट के होते हैं।",
      ar: "العيار المختوم على القطعة أو المطبوع في الفاتورة — عيار 21 أو 22 شائع.",
      bn: "গহনায় ছাপ বা রসিদে লেখা বিশুদ্ধতা — বেশিরভাগ গহনা ২২ ক্যারেট।",
      id: "Kadar yang tertera pada perhiasan atau nota — kebanyakan emas 22K.",
      tr: "Üzerine damgalanmış veya faturada yazılı ayar — çoğu takı 22 ayar.",
      fr: "La pureté inscrite sur la pièce ou sur la facture — la plupart des bijoux sont en 18 ct ou 22 ct.",
    },
    asset_purity_custom: {
      en: "Enter karat, fineness, % or decimal fraction.",
      ur: "کیرٹ، فائننیس، فیصد یا اعشاریہ لکھیں۔",
      hi: "कैरेट, फ़ाइननेस, % या दशमलव लिखें।",
      ar: "أدخل العيار أو النقاوة أو النسبة المئوية.",
      bn: "ক্যারেট, ফাইননেস, % বা দশমিক লিখুন।",
      id: "Masukkan karat, kehalusan, % atau pecahan desimal.",
      tr: "Ayar, saflık, % veya ondalık kesir girin.",
      fr: "Entrez le titre, la finesse, le % ou la fraction décimale.",
    },
    asset_carats: {
      en: "Diamond weight in carats (from the certificate or bill). Leave the value box empty to price automatically.",
      ur: "ہیرے کا وزن کیرٹ میں (سرٹیفکیٹ یا بل سے)۔ قیمت خالی چھوڑیں تو خود حساب ہوگا۔",
      hi: "हीरे का वज़न कैरेट में (सर्टिफ़िकेट या बिल से)। कीमत खाली छोड़ें तो खुद हिसाब होगा।",
      ar: "وزن الماس بالقيراط (من الشهادة أو الفاتورة). اترك القيمة فارغة لحسابها تلقائياً.",
      bn: "হীরার ওজন ক্যারেটে (সার্টিফিকেট বা রসিদ থেকে)। মূল্য খালি রাখলে নিজে হিসাব হবে।",
      id: "Berat berlian dalam karat (dari sertifikat atau nota). Kosongkan nilai untuk penetapan harga otomatis.",
      tr: "Karat cinsinden elmas ağırlığı (sertifika veya faturadan). Otomatik fiyatlandırma için değer kutusunu boş bırakın.",
      fr: "Poids du diamant en carats (d'après le certificat ou la facture). Laissez le champ valeur vide pour une estimation automatique.",
    },
    asset_quantity: {
      en: "How many animals you own in total.",
      ur: "کل کتنے جانور ہیں۔",
      hi: "कुल कितने जानवर हैं।",
      ar: "كم عدد الحيوانات التي تملكها.",
      bn: "মোট কতগুলো পশু আছে।",
      id: "Jumlah total hewan ternak yang dimiliki.",
      tr: "Sahip olduğunuz toplam hayvan sayısı.",
      fr: "Nombre total d'animaux possédés.",
    },
    asset_hawl: {
      en: "Since when have you owned this? Zakat is due only after one lunar year (≈354 days) of owning it. Leave empty if unsure — it will still be counted.",
      ur: "یہ کب سے آپ کے پاس ہے؟ زکوٰۃ ایک قمری سال (تقریباً 354 دن) گزرنے پر فرض ہوتی ہے۔ یقین نہ ہو تو خالی چھوڑیں — پھر بھی شمار ہوگا۔",
      hi: "यह कब से आपके पास है? ज़कात एक चाँद-साल (लगभग 354 दिन) बीतने पर फ़र्ज़ होती है। पक्का पता न हो तो खाली छोड़ें — फिर भी गिना जाएगा।",
      ar: "منذ متى تملك هذا؟ تجب الزكاة بعد سنة قمرية (نحو 354 يوماً) من الملك. اتركه فارغاً إن لم تتأكد — وسيُحسب مع ذلك.",
      bn: "এটি কবে থেকে আপনার কাছে? এক চান্দ্র বছর (প্রায় ৩৫৪ দিন) পর যাকাত ফরজ হয়। নিশ্চিত না হলে খালি রাখুন — তবুও গণনা হবে।",
      id: "Sudah berapa lama Anda memiliki ini? Zakat hanya wajib setelah satu tahun lunar (≈354 hari). Kosongkan jika tidak yakin — tetap akan dihitung.",
      tr: "Bu ne zamandan beri sizde? Zekât yalnızca bir kamerî yıl (≈354 gün) sahip olduktan sonra farz olur. Emin değilseniz boş bırakın — yine de sayılır.",
      fr: "Depuis quand possédez-vous ceci ? La Zakât n'est due qu'après une année lunaire (≈354 jours). Laissez vide si incertain — il sera tout de même compté.",
    },
    asset_acquired: {
      en: "The year you first got this — used only for history charts. Optional.",
      ur: "جس سال یہ ملا — صرف چارٹس کے لیے۔ اختیاری۔",
      hi: "जिस साल यह मिला — सिर्फ़ चार्ट के लिए। ऐच्छिक।",
      ar: "سنة حصولك عليه — للرسوم البيانية فقط. اختياري.",
      bn: "যে বছর এটি পেয়েছেন — শুধু চার্টের জন্য। ঐচ্ছিক।",
      id: "Tahun pertama memperolehnya — hanya untuk grafik riwayat. Opsional.",
      tr: "İlk edindiğiniz yıl — yalnızca geçmiş grafikleri için. İsteğe bağlı.",
      fr: "L'année où vous l'avez obtenu — uniquement pour les graphiques historiques. Facultatif.",
    },
    asset_jewelry: {
      en: "Tick if it is jewellery worn regularly. Shafi'i, Maliki and Hanbali schools exempt worn jewellery; Hanafi counts it.",
      ur: "اگر یہ روزانہ پہننے کا زیور ہے تو نشان لگائیں۔ شافعی، مالکی اور حنبلی میں معاف، حنفی میں شامل۔",
      hi: "अगर यह रोज़ पहनने का गहना है तो टिक करें। शाफ़ेई, मालिकी, हंबली में माफ़़, हनफ़ी में शामिल।",
      ar: "ضع علامة إن كان حلياً يُلبس عادة. الشافعية والمالكية والحنابلة يعفونه، والحنفية يحسبونه.",
      bn: "নিয়মিত পরা গহনা হলে টিক দিন। শাফেয়ী, মালেকী, হাম্বলীতে মাফ; হানাফীতে গণনা হয়।",
      id: "Centang jika ini adalah perhiasan yang dipakai sehari-hari. Mazhab Syafi'i, Maliki, dan Hanbali membebaskan perhiasan yang dipakai; Hanafi menghitungnya.",
      tr: "Düzenli giyilen bir takıysa işaretleyin. Şafiî, Malikî ve Hanbelî mezhepleri giyilen takıyı muaf tutar; Hanefî sayar.",
      fr: "Cochez s'il s'agit de bijoux portés régulièrement. Les écoles shafi'ite, malikite et hanbalite exemptent les bijoux portés ; l'école hanafite les inclut.",
    },
    asset_pf_balance: {
      en: "Copy the balance from your latest PF/EPF statement or passbook.",
      ur: "اپنے تازہ PF/EPF اسٹیٹمنٹ یا پاس بک سے بیلنس لکھیں۔",
      hi: "अपने ताज़ा PF/EPF स्टेटमेंट या पासबुक से बैलेंस लिखें।",
      ar: "انقل الرصيد من أحدث كشف لصندوق الادخار.",
      bn: "সর্বশেষ PF/EPF স্টেটমেন্ট থেকে ব্যালেন্স লিখুন।",
      id: "Salin saldo dari laporan BPJS Ketenagakerjaan/PF terbaru Anda.",
      tr: "En son BES/SGK bildirgenizdeki bakiyeyi kopyalayın.",
      fr: "Copiez le solde de votre dernier relevé d'épargne retraite.",
    },
    asset_pf_asof: {
      en: "The date printed on that statement — the app projects today's balance from it.",
      ur: "اس اسٹیٹمنٹ پر لکھی تاریخ — ایپ اس سے آج کا بیلنس نکالتی ہے۔",
      hi: "उस स्टेटमेंट पर छपी तारीख — ऐप इससे आज का बैलेंस निकालती है।",
      ar: "التاريخ المطبوع في الكشف — يقدّر التطبيق رصيد اليوم منه.",
      bn: "স্টেটমেন্টের তারিখ — এর থেকে অ্যাপ আজকের ব্যালেন্স বের করে।",
      id: "Tanggal pada laporan tersebut — aplikasi memproyeksikan saldo hari ini darinya.",
      tr: "O bildirgede yazılı tarih — uygulama bugünkü bakiyeyi buradan tahmin eder.",
      fr: "La date imprimée sur ce relevé — l'application projette le solde d'aujourd'hui à partir de celui-ci.",
    },
    asset_pf_monthly: {
      en: "The amount added every month — see your salary slip.",
      ur: "ہر ماہ جمع ہونے والی رقم — تنخواہ سلپ دیکھیں۔",
      hi: "हर महीने जमा होने वाली राशि — सैलरी स्लिप देखें।",
      ar: "المبلغ المضاف كل شهر — انظر قسيمة الراتب.",
      bn: "প্রতি মাসে জমা হওয়া টাকা — স্যালারি স্লিপ দেখুন।",
      id: "Jumlah yang ditambahkan setiap bulan — lihat slip gaji.",
      tr: "Her ay eklenen tutar — maaş bordronuza bakın.",
      fr: "Le montant ajouté chaque mois — voir votre bulletin de salaire.",
    },
    asset_pf_rate: {
      en: "Yearly interest rate of the fund — EPF India is about 8.25%.",
      ur: "فنڈ کی سالانہ شرح — EPF انڈیا تقریباً 8.25% ہے۔",
      hi: "फ़ंड की सालाना दर — EPF इंडिया लगभग 8.25% है।",
      ar: "معدل الفائدة السنوي للصندوق.",
      bn: "ফান্ডের বার্ষিক হার — EPF ইন্ডিয়া প্রায় ৮.২৫%।",
      id: "Tingkat bunga tahunan dana — BPJS sekitar 5,5–7%.",
      tr: "Fonun yıllık faiz oranı — BES yaklaşık %8–12.",
      fr: "Taux d'intérêt annuel du fonds.",
    },
    asset_photo: {
      en: "Optional photo of the item. Stored only in your browser and included in Excel backups.",
      ur: "چیز کی تصویر (اختیاری)۔ صرف آپ کے براؤزر میں محفوظ اور ایکسل بیک اپ میں شامل۔",
      hi: "चीज़ की फ़ोटो (ऐच्छिक)। सिर्फ़ आपके ब्राउज़र में सुरक्षित, एक्सेल बैकअप में शामिल।",
      ar: "صورة اختيارية. تُحفظ في متصفحك فقط وتُضمّن في النسخ الاحتياطية.",
      bn: "জিনিসের ছবি (ঐচ্ছিক)। শুধু আপনার ব্রাউজারে থাকে, এক্সেল ব্যাকআপে যুক্ত হয়।",
      id: "Foto opsional. Tersimpan hanya di browser dan disertakan dalam cadangan Excel.",
      tr: "İsteğe bağlı fotoğraf. Yalnızca tarayıcınızda saklanır ve Excel yedeklerine dahil edilir.",
      fr: "Photo facultative. Stockée uniquement dans votre navigateur et incluse dans les sauvegardes Excel.",
    },
    asset_subtype_property: {
      en: "Personal residence = the house you live in (no zakat). Rental = you collect rent (building exempt; add saved rent under Cash). Trade = bought to sell (full value counts).",
      ur: "ذاتی رہائش = جس گھر میں رہتے ہیں (زکوٰۃ نہیں)۔ کرایہ = عمارت معاف، بچا ہوا کرایہ نقدی میں لکھیں۔ تجارت = بیچنے کے لیے خریدی — پوری قیمت شمار ہوگی۔",
      hi: "निजी आवास = जिस घर में रहते हैं (ज़कात नहीं)। किराया = इमारत माफ़, बचा किराया नक़दी में जोड़ें। व्यापार = बेचने के लिए खरीदी — पूरी कीमत गिनी जाएगी।",
      ar: "سكن شخصي = البيت الذي تسكنه (لا زكاة). إيجار = المبنى معفى، وأضف الإيجار المدّخر في النقد. تجارة = اشتُري للبيع — تُحسب القيمة كاملة.",
      bn: "নিজ বাসস্থান = যে বাড়িতে থাকেন (যাকাত নেই)। ভাড়া = ভবন মাফ, জমানো ভাড়া নগদে যোগ করুন। ব্যবসা = বিক্রির জন্য কেনা — পুরো মূল্য গণনা হয়।",
      id: "Tempat tinggal = rumah yang ditinggali (tidak ada zakat). Sewa = gedung bebas; tambahkan uang sewa yang ditabung di Kas. Dagang = dibeli untuk dijual — nilai penuh dihitung.",
      tr: "Oturduğunuz ev (zekât yok). Kiralık = bina muaf; biriktirilen kira gelirini Nakit olarak ekleyin. Ticaret = satmak için alındı — tam değer sayılır.",
      fr: "Résidence personnelle = pas de Zakât. Location = bâtiment exempté ; ajoutez le loyer épargné sous Trésorerie. Commerce = acheté pour revendre — la valeur totale compte.",
    },
    asset_subtype_agri: {
      en: "How the land was watered: rain-fed pays 10%, irrigated 5%, mixed 7.5%.",
      ur: "زمین کو پانی کیسے ملا: بارش سے 10%، آب پاشی سے 5%، ملا جلا 7.5%۔",
      hi: "ज़मीन को पानी कैसे मिला: बारिश से 10%, सिंचाई से 5%, मिला-जुला 7.5%।",
      ar: "طريقة السقي: بالمطر 10%، بالري 5%، مختلط 7.5%.",
      bn: "জমিতে পানি কীভাবে এল: বৃষ্টিতে ১০%, সেচে ৫%, মিশ্র ৭.৫%।",
      id: "Cara pengairan tanah: hujan 10%, irigasi 5%, campuran 7,5%.",
      tr: "Arazinin sulanma biçimi: yağmurla %10, sulama ile %5, karışık %7,5.",
      fr: "Mode d'irrigation de la terre : eau de pluie 10 %, irrigation 5 %, mixte 7,5 %.",
    },
    asset_subtype_livestock: {
      en: "Which animal — the Sunnah sets different zakat counts for sheep/goats, cattle and camels.",
      ur: "کون سا جانور — بھیڑ بکری، گائے اور اونٹ کے لیے سنت میں الگ الگ حساب ہے۔",
      hi: "कौन सा जानवर — भेड़-बकरी, गाय और ऊँट के लिए सुन्नत में अलग-अलग हिसाब है।",
      ar: "أي حيوان — فللغنم والبقر والإبل أنصبة مختلفة في السنة.",
      bn: "কোন পশু — ভেড়া-ছাগল, গরু ও উটের জন্য সুন্নাহতে আলাদা হিসাব।",
      id: "Hewan apa — kambing/domba, sapi, dan unta memiliki ketentuan berbeda dalam Sunnah.",
      tr: "Hangi hayvan — Sünnet'te koyun/keçi, sığır ve deve için farklı nisaplar var.",
      fr: "Quel animal — la Sunna fixe des seuils différents pour les ovins/caprins, les bovins et les chameaux.",
    },

    // ---- Payment form ----
    pay_intro: {
      en: "Already gave zakat this year? Record it here — it is subtracted from the amount due.",
      ur: "اس سال زکوٰۃ دے چکے ہیں؟ یہاں لکھیں — وہ واجب رقم سے کم ہو جائے گی۔",
      hi: "इस साल ज़कात दे चुके हैं? यहाँ लिखें — वह देय राशि से घट जाएगी।",
      ar: "هل دفعت زكاة هذا العام؟ سجّلها هنا — وتُخصم من المبلغ المستحق.",
      bn: "এ বছর যাকাত দিয়েছেন? এখানে লিখুন — দেয় অর্থ থেকে বাদ যাবে।",
      id: "Sudah bayar zakat tahun ini? Catat di sini — dikurangkan dari jumlah yang harus dibayar.",
      tr: "Bu yıl zekât verdiniz mi? Burada kaydedin — ödenecek tutardan düşülür.",
      fr: "Vous avez déjà versé la Zakât cette année ? Enregistrez-la ici — elle est déduite du montant dû.",
    },
    pay_given: {
      en: "Who received it — a person in need, masjid, madrasa or charity.",
      ur: "کس کو دی — ضرورت مند شخص، مسجد، مدرسہ یا خیراتی ادارہ۔",
      hi: "किसे दी — ज़रूरतमंद व्यक्ति, मस्जिद, मदरसा या संस्था।",
      ar: "من استلمها — محتاج، مسجد، مدرسة أو جمعية خيرية.",
      bn: "কাকে দিয়েছেন — অভাবী ব্যক্তি, মসজিদ, মাদ্রাসা বা সংস্থা।",
      id: "Siapa yang menerimanya — orang yang membutuhkan, masjid, pesantren, atau lembaga amal.",
      tr: "Kim aldı — ihtiyaç sahibi, cami, medrese veya hayır kurumu.",
      fr: "Qui l'a reçue — une personne dans le besoin, une mosquée, une madrasa ou une association.",
    },
    pay_amount: {
      en: "How much you gave.",
      ur: "کتنی رقم دی۔",
      hi: "कितनी राशि दी।",
      ar: "كم دفعت.",
      bn: "কত টাকা দিয়েছেন।",
      id: "Berapa yang Anda berikan.",
      tr: "Ne kadar verdiğiniz.",
      fr: "Le montant que vous avez donné.",
    },

    // ---- Category explainers ----
    cat_Gold: {
      en: "Gold you own — jewellery, coins, bars. Enter the weight in grams and the karat; the app prices it at today's gold rate.",
      ur: "آپ کا سونا — زیورات، سکے، بسکٹ۔ وزن گرام میں اور کیرٹ لکھیں — آج کے ریٹ سے قیمت خود بنے گی۔",
      hi: "आपका सोना — गहने, सिक्के, बिस्कुट। वज़न ग्राम में और कैरेट लिखें — आज के रेट से कीमत खुद बनेगी।",
      ar: "الذهب الذي تملكه — حلي، عملات، سبائك. أدخل الوزن بالجرام والعيار — ويُقيّم بسعر اليوم.",
      bn: "আপনার সোনা — গহনা, মুদ্রা, বার। ওজন গ্রামে ও ক্যারেট লিখুন — আজকের দরে দাম হবে।",
      id: "Emas yang dimiliki — perhiasan, koin, batangan. Masukkan berat gram dan kadar; aplikasi menilai dengan harga emas hari ini.",
      tr: "Sahip olduğunuz altın — takı, sikke, külçe. Gram ve ayar girin; uygulama bugünkü altın kuruyla değer biçer.",
      fr: "L'or que vous possédez — bijoux, pièces, lingots. Entrez le poids en grammes et le titre ; l'application évalue au cours de l'or du jour.",
    },
    cat_Silver: {
      en: "Silver items — jewellery, coins, utensils. Enter weight and purity; today's silver rate is applied automatically.",
      ur: "چاندی — زیور، سکے، برتن۔ وزن اور خالصیت لکھیں — آج کا ریٹ خود لگے گا۔",
      hi: "चाँदी — गहने, सिक्के, बर्तन। वज़न और शुद्धता लिखें — आज का रेट खुद लगेगा।",
      ar: "الفضة — حلي، عملات، أوانٍ. أدخل الوزن والنقاوة — ويُطبّق سعر اليوم.",
      bn: "রূপা — গহনা, মুদ্রা, বাসন। ওজন ও বিশুদ্ধতা লিখুন — আজকের দর লাগবে।",
      id: "Barang perak — perhiasan, koin, peralatan. Masukkan berat dan kadar; harga perak hari ini diterapkan otomatis.",
      tr: "Gümüş eşyalar — takı, sikke, sofra takımı. Ağırlık ve saflığı girin; bugünkü gümüş kuru otomatik uygulanır.",
      fr: "Articles en argent — bijoux, pièces, couverts. Entrez le poids et la pureté ; le cours de l'argent du jour est appliqué automatiquement.",
    },
    cat_Platinum: {
      en: "Platinum items. Enter weight and purity; valued at today's rate.",
      ur: "پلاٹینم — وزن اور خالصیت لکھیں، آج کے ریٹ سے قیمت بنے گی۔",
      hi: "प्लेटिनम — वज़न और शुद्धता लिखें, आज के रेट से कीमत बनेगी।",
      ar: "البلاتين — أدخل الوزن والنقاوة، ويُقيّم بسعر اليوم.",
      bn: "প্লাটিনাম — ওজন ও বিশুদ্ধতা লিখুন, আজকের দরে দাম হবে।",
      id: "Barang platinum. Masukkan berat dan kadar; dinilai dengan harga hari ini.",
      tr: "Platin eşyalar. Ağırlık ve saflığı girin; bugünkü kurla değerlenir.",
      fr: "Articles en platine. Entrez le poids et la pureté ; valorisé au cours du jour.",
    },
    cat_Diamond: {
      en: "Diamond jewellery or stones. Enter carats to price automatically, or type today's resale value.",
      ur: "ہیرے کا زیور یا نگ۔ کیرٹ لکھیں تو قیمت خود بنے گی، یا آج کی قیمت خود لکھیں۔",
      hi: "हीरे का गहना या नग। कैरेट लिखें तो कीमत खुद बनेगी, या आज की कीमत खुद लिखें।",
      ar: "حلي أو أحجار الماس. أدخل القيراط للتقييم التلقائي، أو اكتب قيمة البيع اليوم.",
      bn: "হীরার গহনা বা পাথর। ক্যারেট লিখলে দাম নিজে হবে, নয়তো আজকের বিক্রয় মূল্য লিখুন।",
      id: "Perhiasan atau batu berlian. Masukkan karat untuk penetapan harga otomatis, atau ketik nilai jual hari ini.",
      tr: "Elmas takı veya taşlar. Otomatik fiyatlandırma için karat girin ya da bugünkü ikinci el değerini yazın.",
      fr: "Bijoux ou pierres en diamant. Entrez les carats pour une évaluation automatique, ou saisissez la valeur de revente du jour.",
    },
    cat_Livestock: {
      en: "Sheep, goats, cattle or camels kept for milk or breeding. Enter how many and the value of one animal — the Sunnah tiers are applied.",
      ur: "دودھ یا افزائش کے لیے بھیڑ بکری، گائے یا اونٹ۔ تعداد اور فی جانور قیمت لکھیں — سنت کے حساب سے زکوٰۃ بنے گی۔",
      hi: "दूध या प्रजनन के लिए भेड़-बकरी, गाय या ऊँट। संख्या और प्रति जानवर कीमत लिखें — सुन्नत के हिसाब से ज़कात बनेगी।",
      ar: "غنم أو بقر أو إبل للحليب أو التربية. أدخل العدد وقيمة الرأس — وتُطبّق أنصبة السنة.",
      bn: "দুধ বা প্রজননের জন্য ভেড়া-ছাগল, গরু বা উট। সংখ্যা ও প্রতি পশুর দাম লিখুন।",
      id: "Kambing, domba, sapi, atau unta yang dipelihara untuk susu atau perkembangbiakan. Masukkan jumlah dan nilai per hewan — tingkat Sunnah diterapkan.",
      tr: "Süt veya üretim için beslenen koyun, keçi, sığır veya deve. Adet ve hayvan başı değeri girin — Sünnet kademeleri uygulanır.",
      fr: "Moutons, chèvres, bovins ou chameaux pour le lait ou la reproduction. Entrez le nombre et la valeur par animal — les paliers de la Sunna s'appliquent.",
    },
    cat_Agriculture: {
      en: "Crops you harvested. Enter the harvest value; rain-fed land pays 10%, irrigated 5%. No one-year wait — due at harvest.",
      ur: "فصل کی پیداوار۔ پیداوار کی قیمت لکھیں — بارانی زمین 10%، آب پاشی 5%۔ سال کا انتظار نہیں — کٹائی پر واجب۔",
      hi: "कटी हुई फ़सल। पैदावार की कीमत लिखें — बारिश वाली ज़मीन 10%, सिंचित 5%। साल का इंतज़ार नहीं — कटाई पर देय।",
      ar: "المحصول. أدخل قيمته — المسقي بالمطر 10% وبالري 5%. لا تنتظر سنة — تجب عند الحصاد.",
      bn: "কাটা ফসল। ফসলের মূল্য লিখুন — বৃষ্টির জমি ১০%, সেচের ৫%। বছরের অপেক্ষা নেই।",
      id: "Tanaman yang dipanen. Masukkan nilai panen; lahan tadah hujan 10%, irigasi 5%. Tidak perlu menunggu satu tahun — wajib saat panen.",
      tr: "Hasat ettiğiniz ürünler. Hasat değerini girin; yağmurla sulanan %10, sulamalı %5. Bir yıl bekleme yok — hasatta farz.",
      fr: "Récoltes. Entrez la valeur de la récolte ; terres pluviales 10 %, irriguées 5 %. Pas d'attente d'un an — dû à la récolte.",
    },
    cat_Cash: {
      en: "Money in hand, bank accounts and fixed deposits. Enter the total you hold today — not your monthly salary.",
      ur: "ہاتھ میں نقدی، بینک اکاؤنٹ اور FD۔ آج جو کل رقم موجود ہے وہ لکھیں — ماہانہ تنخواہ نہیں۔",
      hi: "हाथ की नक़दी, बैंक खाते और FD। आज जो कुल राशि मौजूद है वह लिखें — मासिक सैलरी नहीं।",
      ar: "النقد في اليد والحسابات والودائع. أدخل المجموع الذي تملكه اليوم — لا راتبك الشهري.",
      bn: "হাতের নগদ, ব্যাংক অ্যাকাউন্ট ও FD। আজ মোট যা আছে তা লিখুন — মাসিক বেতন নয়।",
      id: "Uang tunai, rekening bank, dan deposito. Masukkan total yang dimiliki hari ini — bukan gaji bulanan.",
      tr: "Nakit, banka hesapları ve vadeli mevduat. Bugün sahip olduğunuz toplam tutarı girin — aylık maaşınızı değil.",
      fr: "Argent liquide, comptes bancaires et dépôts à terme. Entrez le total que vous détenez aujourd'hui — pas votre salaire mensuel.",
    },
    cat_PF: {
      en: "Provident fund (PF/EPF). Enter the balance from your statement and the monthly contributions — the app estimates today's balance.",
      ur: "پراویڈنٹ فنڈ (PF/EPF)۔ اسٹیٹمنٹ کا بیلنس اور ماہانہ جمع رقم لکھیں — ایپ آج کا اندازہ لگائے گی۔",
      hi: "प्रोविडेंट फ़ंड (PF/EPF)। स्टेटमेंट का बैलेंस और मासिक जमा लिखें — ऐप आज का अनुमान लगाएगी।",
      ar: "صندوق الادخار. أدخل رصيد الكشف والاشتراكات الشهرية — ويُقدّر التطبيق رصيد اليوم.",
      bn: "প্রভিডেন্ট ফান্ড (PF/EPF)। স্টেটমেন্টের ব্যালেন্স ও মাসিক জমা লিখুন।",
      id: "Dana pensiun/BPJS. Masukkan saldo dari laporan dan iuran bulanan — aplikasi memperkirakan saldo hari ini.",
      tr: "Bireysel emeklilik (BES/SGK). Bildirgenizdeki bakiyeyi ve aylık katkıları girin — uygulama bugünkü bakiyeyi tahmin eder.",
      fr: "Épargne retraite. Entrez le solde de votre relevé et les cotisations mensuelles — l'application estime le solde d'aujourd'hui.",
    },
    cat_Stocks: {
      en: "Shares, mutual funds and similar investments. Enter today's total value shown in your broker or fund app.",
      ur: "حصص، میوچول فنڈ وغیرہ۔ بروکر ایپ میں آج کی کل قیمت لکھیں۔",
      hi: "शेयर, म्यूचुअल फ़ंड आदि। ब्रोकर ऐप में दिख रही आज की कुल कीमत लिखें।",
      ar: "الأسهم والصناديق الاستثمارية. أدخل القيمة الإجمالية اليوم من تطبيق الوسيط.",
      bn: "শেয়ার, মিউচুয়াল ফান্ড ইত্যাদি। ব্রোকার অ্যাপে আজকের মোট মূল্য লিখুন।",
      id: "Saham, reksa dana, dan investasi sejenis. Masukkan nilai total hari ini dari aplikasi broker.",
      tr: "Hisseler, yatırım fonları ve benzeri yatırımlar. Aracı kurum uygulamanızdaki bugünkü toplam değeri girin.",
      fr: "Actions, fonds communs de placement et investissements similaires. Entrez la valeur totale d'aujourd'hui de votre application de courtage.",
    },
    cat_Business: {
      en: "Goods kept for sale plus business cash. Enter today's resale value of the stock — not the shop building or machines.",
      ur: "بیچنے کا مال اور کاروباری نقدی۔ اسٹاک کی آج کی قیمت لکھیں — دکان کی عمارت یا مشینیں نہیں۔",
      hi: "बेचने का माल और कारोबारी नक़दी। स्टॉक की आज की कीमत लिखें — दुकान की इमारत या मशीनें नहीं।",
      ar: "بضاعة التجارة ونقد العمل. أدخل قيمة البضاعة اليوم — لا المبنى ولا الآلات.",
      bn: "বিক্রির পণ্য ও ব্যবসার নগদ। স্টকের আজকের মূল্য লিখুন — দোকানের ভবন বা যন্ত্র নয়।",
      id: "Barang dagangan dan kas bisnis. Masukkan nilai jual kembali stok hari ini — bukan gedung toko atau mesin.",
      tr: "Satış için tutulan mallar ve iş nakdi. Stokun bugünkü yeniden satış değerini girin — dükkan binasını veya makineleri değil.",
      fr: "Marchandises destinées à la vente et trésorerie d'entreprise. Entrez la valeur de revente du stock aujourd'hui — pas le bâtiment ni les machines.",
    },
    cat_Property: {
      en: "Only property bought to resell counts fully for zakat. Your own home is exempt; for rentals the building is exempt — add saved rent under Cash.",
      ur: "صرف بیچنے کے لیے خریدی جائیداد پر پوری زکوٰۃ۔ اپنا گھر معاف؛ کرایے کی عمارت بھی معاف — بچا ہوا کرایہ نقدی میں لکھیں۔",
      hi: "सिर्फ़ बेचने के लिए खरीदी प्रॉपर्टी पर पूरी ज़कात। अपना घर माफ़; किराए की इमारत भी माफ़ — बचा किराया नक़दी में जोड़ें।",
      ar: "العقار المشترى للبيع فقط تجب فيه الزكاة كاملة. بيتك معفى، ومبنى الإيجار معفى — أضف الإيجار المدّخر في النقد.",
      bn: "শুধু বিক্রির জন্য কেনা সম্পত্তিতে পূর্ণ যাকাত। নিজের বাড়ি মাফ; ভাড়ার ভবনও মাফ — জমানো ভাড়া নগদে যোগ করুন।",
      id: "Hanya properti yang dibeli untuk dijual kembali yang sepenuhnya dikenai zakat. Rumah Anda sendiri bebas; untuk sewaan gedung bebas — tambahkan sewa yang ditabung di Kas.",
      tr: "Yalnızca yeniden satmak için alınan mülk zekât için tam sayılır. Kendi eviniz muaftır; kira için bina muaftır — biriktirilen kira gelirini Nakit olarak ekleyin.",
      fr: "Seul le bien acheté pour être revendu compte pleinement pour la Zakât. Votre domicile est exempté ; pour les locations, le bâtiment est exempté — ajoutez le loyer épargné sous Trésorerie.",
    },
    cat_Partnership: {
      en: "Your share in a joint business. Enter what your share is worth today.",
      ur: "مشترکہ کاروبار میں آپ کا حصہ۔ آج اس حصے کی قیمت لکھیں۔",
      hi: "साझे कारोबार में आपका हिस्सा। आज उस हिस्से की कीमत लिखें।",
      ar: "حصتك في شراكة. أدخل قيمة حصتك اليوم.",
      bn: "যৌথ ব্যবসায় আপনার অংশ। আজ তার মূল্য লিখুন।",
      id: "Bagian Anda dalam bisnis bersama. Masukkan nilai bagian Anda hari ini.",
      tr: "Ortak işletmedeki payınız. Payınızın bugünkü değerini girin.",
      fr: "Votre part dans une entreprise commune. Entrez la valeur de votre part aujourd'hui.",
    },
    cat_Rikaz: {
      en: "Buried treasure or found valuables — rare. 20% is due once, immediately; no one-year wait.",
      ur: "دفن خزانہ یا ملا ہوا مال — نادر۔ 20% ایک بار فوراً واجب؛ سال کا انتظار نہیں۔",
      hi: "दबा खज़ाना या मिला माल — दुर्लभ। 20% एक बार तुरंत देय; साल का इंतज़ार नहीं।",
      ar: "الركاز — كنز مدفون. فيه الخُمس 20% مرة واحدة فوراً، بلا انتظار سنة.",
      bn: "পোঁতা গুপ্তধন — বিরল। ২০% একবার সঙ্গে সঙ্গে দেয়; বছরের অপেক্ষা নেই।",
      id: "Harta karun yang ditemukan — jarang. 20% wajib sekali, segera; tidak perlu menunggu satu tahun.",
      tr: "Gömülü hazine veya bulunan değerliler — nadir. %20 bir kez, hemen farz; bir yıl bekleme yok.",
      fr: "Trésor enfoui ou objets de valeur trouvés — rare. 20 % dus une fois, immédiatement ; pas d'attente d'un an.",
    },
    cat_Liabilities: {
      en: "Money you owe — loans, credit card dues, borrowed money. Depending on your school, this reduces your zakatable wealth.",
      ur: "جو رقم آپ نے دینی ہے — قرض، کریڈٹ کارڈ وغیرہ۔ آپ کے مسلک کے مطابق یہ زکوٰۃ والے مال سے کم ہوتی ہے۔",
      hi: "जो राशि आपको देनी है — लोन, क्रेडिट कार्ड आदि। आपके मसलक के अनुसार यह ज़कात वाले माल से घटती है।",
      ar: "الديون التي عليك — قروض وبطاقات. بحسب مذهبك تُخصم من المال الزكوي.",
      bn: "আপনার ঋণ — লোন, ক্রেডিট কার্ড ইত্যাদি। মাযহাব অনুযায়ী এটি যাকাতযোগ্য সম্পদ কমায়।",
      id: "Uang yang Anda hutangkan — pinjaman, tagihan kartu kredit, uang pinjaman. Tergantung mazhab Anda, ini mengurangi harta yang terkena zakat.",
      tr: "Borçlarınız — krediler, kredi kartı borçları, ödünç alınan para. Mezhebinize bağlı olarak bu, zekâta tabi servetinizi azaltır.",
      fr: "Argent que vous devez — prêts, dettes de carte de crédit, argent emprunté. Selon votre école, cela réduit votre richesse soumise à la Zakât.",
    },

    // ---- Site chrome: header, nav, Dashboard, Rates top section ----
    // (this block is translated into en/ur/hi/ar only — the sitewide
    // language switcher does not offer Bengali)
    app_title: {
      en: "Household Zakat Calculator",
      ur: "گھریلو زکوٰۃ کیلکولیٹر",
      hi: "पारिवारिक ज़कात कैलकुलेटर",
      ar: "حاسبة زكاة الأسرة",
      bn: "পারিবারিক যাকাত ক্যালকুলেটর",
      id: "Kalkulator Zakat Keluarga",
      tr: "Aile Zekât Hesaplayıcısı",
      fr: "Calculateur de Zakât familial",
    },
    hero_sub: {
      en: "Purify your wealth · fulfil the third pillar",
      ur: "اپنے مال کو پاک کریں · اسلام کے تیسرے رکن کی ادائیگی کریں",
      hi: "अपने माल को पाक करें · इस्लाम के तीसरे स्तंभ को पूरा करें",
      ar: "زكِّ مالك · وأدِّ الركن الثالث",
      bn: "আপনার সম্পদ পবিত্র করুন · তৃতীয় স্তম্ভ পালন করুন",
      id: "Sucikan hartamu · tunaikan rukun ketiga",
      tr: "Malını arındır · üçüncü farzı eda et",
      fr: "Purifiez votre richesse · accomplissez le troisième pilier",
    },
    nav_dashboard: { en: "Dashboard", ur: "ڈیش بورڈ", hi: "डैशबोर्ड", ar: "لوحة التحكم",
      bn: "ড্যাশবোর্ড",
      id: "Dasbor",
      tr: "Pano",
      fr: "Tableau de bord",
    },
    nav_analytics: { en: "Analytics", ur: "تجزیات", hi: "विश्लेषण", ar: "التحليلات",
      bn: "বিশ্লেষণ",
      id: "Analitik",
      tr: "Analiz",
      fr: "Analytique",
    },
    nav_yearly: { en: "Yearly", ur: "سالانہ", hi: "वार्षिक", ar: "سنوي",
      bn: "বার্ষিক",
      id: "Tahunan",
      tr: "Yıllık",
      fr: "Annuel",
    },
    nav_rates: { en: "Rates", ur: "نرخ", hi: "दरें", ar: "الأسعار",
      bn: "দর",
      id: "Harga Pasar",
      tr: "Kurlar",
      fr: "Cours",
    },
    nav_backup: { en: "Backup", ur: "بیک اپ", hi: "बैकअप", ar: "نسخ احتياطي",
      bn: "ব্যাকআপ",
      id: "Cadangan",
      tr: "Yedek",
      fr: "Sauvegarde",
    },
    nav_about: { en: "About", ur: "تعارف", hi: "परिचय", ar: "حول",
      bn: "পরিচয়",
      id: "Tentang",
      tr: "Hakkında",
      fr: "À propos",
    },
    today_label: { en: "Today", ur: "آج", hi: "आज", ar: "اليوم",
      bn: "আজ",
      id: "Hari ini",
      tr: "Bugün",
      fr: "Aujourd'hui",
    },
    baseline_label: {
      en: "Zakat baseline",
      ur: "زکوٰۃ کی بنیادی تاریخ",
      hi: "ज़कात आधार तिथि",
      ar: "تاريخ استحقاق الزكاة",
      bn: "যাকাত বেসলাইন",
      id: "Acuan zakat",
      tr: "Zekât başlangıcı",
      fr: "Référence zakât",
    },
    household_title: { en: "Your household", ur: "آپ کا گھرانہ", hi: "आपका परिवार", ar: "أسرتك",
      bn: "আপনার পরিবার",
      id: "Keluarga Anda",
      tr: "Haneniz",
      fr: "Votre foyer",
    },
    household_desc: {
      en: "Add and save your family name first — it is required before adding members and assets. It labels this household on screen, in Excel backups, and in reports, and stays on this device unless you export or sync a backup.",
      ur: "سب سے پہلے اپنے خاندان کا نام درج اور محفوظ کریں — افراد اور اثاثے شامل کرنے سے پہلے یہ ضروری ہے۔ یہ نام اس گھرانے کی پہچان کے طور پر اسکرین پر، ایکسل بیک اپ میں اور رپورٹس میں دکھایا جاتا ہے، اور بیک اپ ایکسپورٹ یا سِنک کیے بغیر صرف اسی ڈیوائس پر محفوظ رہتا ہے۔",
      hi: "सबसे पहले अपने परिवार का नाम दर्ज करके सेव करें — सदस्य और संपत्ति जोड़ने से पहले यह ज़रूरी है। यह नाम इस घर की पहचान के तौर पर स्क्रीन पर, एक्सेल बैकअप में और रिपोर्ट्स में दिखता है, और बैकअप एक्सपोर्ट या सिंक किए बिना केवल इसी डिवाइस पर सुरक्षित रहता है।",
      ar: "أدخل اسم عائلتك واحفظه أولاً — وهو مطلوب قبل إضافة الأفراد والممتلكات. يُستخدم هذا الاسم لتمييز الأسرة على الشاشة، وفي نسخ إكسل الاحتياطية، وفي التقارير، ويبقى على هذا الجهاز ما لم تُصدِّر أو تُزامن نسخة احتياطية.",
      bn: "আগে আপনার পারিবারিক নাম যোগ করুন ও সেভ করুন — সদস্য ও সম্পদ যোগ করার আগে এটি দরকার। স্ক্রিনে, এক্সেল ব্যাকআপে ও রিপোর্টে দেখায়, এবং ব্যাকআপ এক্সপোর্ট বা সিঙ্ক না করলে শুধু এই ডিভাইসে থাকে।",
      id: "Tambahkan dan simpan nama keluarga terlebih dahulu — diperlukan sebelum menambahkan anggota dan aset. Nama ini menandai rumah tangga di layar, cadangan Excel, dan laporan, dan tetap di perangkat ini kecuali Anda mengekspor atau menyinkronkan cadangan.",
      tr: "Önce aile adınızı ekleyin ve kaydedin — üye ve varlık eklemeden önce bu gereklidir. Bu ad ekranı, Excel yedekleri ve raporlardaki hane kimliğidir; bir yedeği dışa aktarmadığınız sürece yalnızca bu cihazda kalır.",
      fr: "Commencez par saisir et enregistrer le nom de famille — il est obligatoire avant d'ajouter des membres et des biens. Il identifie ce foyer à l'écran, dans les sauvegardes Excel et dans les rapports, et reste sur cet appareil sauf si vous exportez ou synchronisez une sauvegarde.",
    },
    family_name_field_label: {
      en: "Family name (required)",
      ur: "خاندان کا نام (لازمی)",
      hi: "परिवार का नाम (आवश्यक)",
      ar: "اسم العائلة (مطلوب)",
      bn: "পারিবারিক নাম (আবশ্যক)",
      id: "Nama keluarga (wajib)",
      tr: "Aile adı (zorunlu)",
      fr: "Nom de famille (obligatoire)",
    },
    family_name_help: {
      en: "Family or surname only — for example SMY FAMILY. Individual member names are added separately below.",
      ur: "صرف خاندان یا کنیت کا نام — مثال کے طور پر SMY FAMILY۔ ہر فرد کا نام الگ سے نیچے درج کیا جائے گا۔",
      hi: "केवल परिवार या उपनाम — उदाहरण के लिए SMY FAMILY। हर सदस्य का नाम अलग से नीचे जोड़ा जाएगा।",
      ar: "اسم العائلة فقط — مثال: SMY FAMILY. تُضاف أسماء الأفراد كل على حدة أدناه.",
      bn: "শুধু পারিবারিক বা পদবি — উদাহরণ: SMY FAMILY। প্রতিটি সদস্যের নাম নিচে আলাদাভাবে যোগ করা হবে।",
      id: "Nama keluarga atau marga saja — misalnya KELUARGA AHMAD. Nama anggota individu ditambahkan secara terpisah di bawah.",
      tr: "Yalnızca aile veya soyadı — örneğin YILMAZ AİLESİ. Bireysel üye adları aşağıda ayrıca eklenir.",
      fr: "Nom de famille uniquement — par exemple FAMILLE MARTIN. Les noms des membres sont ajoutés séparément ci-dessous.",
    },
    save_family_name_btn: {
      en: "Save family name",
      ur: "خاندان کا نام محفوظ کریں",
      hi: "परिवार का नाम सेव करें",
      ar: "حفظ اسم العائلة",
      bn: "পারিবারিক নাম সেভ করুন",
      id: "Simpan nama keluarga",
      tr: "Aile adını kaydet",
      fr: "Enregistrer le nom de famille",
    },
    toast_family_saved: {
      en: "Family name saved",
      ur: "خاندان کا نام محفوظ ہو گیا",
      hi: "परिवार का नाम सेव हो गया",
      ar: "تم حفظ اسم العائلة",
      bn: "পারিবারিক নাম সেভ হয়েছে",
      id: "Nama keluarga tersimpan",
      tr: "Aile adı kaydedildi",
      fr: "Nom de famille enregistré",
    },
    toast_family_enter: {
      en: "Enter a family name",
      ur: "خاندان کا نام درج کریں",
      hi: "परिवार का नाम दर्ज करें",
      ar: "أدخل اسم العائلة",
      bn: "পারিবারিক নাম দিন",
      id: "Masukkan nama keluarga",
      tr: "Bir aile adı girin",
      fr: "Saisissez un nom de famille",
    },
    prefs_title: {
      en: "Currency, language & school",
      ur: "کرنسی، زبان اور مسلک",
      hi: "मुद्रा, भाषा और मसलक",
      ar: "العملة واللغة والمذهب",
      bn: "মুদ্রা, ভাষা ও মাযহাব",
      id: "Mata uang, bahasa & mazhab",
      tr: "Para birimi, dil ve mezhep",
      fr: "Devise, langue et école juridique",
    },
    currency_label: { en: "Currency", ur: "کرنسی", hi: "मुद्रा", ar: "العملة",
      bn: "মুদ্রা",
      id: "Mata uang",
      tr: "Para birimi",
      fr: "Devise",
    },
    lang_field_label: { en: "Language", ur: "زبان", hi: "भाषा", ar: "اللغة",
      bn: "ভাষা",
      id: "Bahasa",
      tr: "Dil",
      fr: "Langue",
    },
    lang_field_help: {
      en: "Applies across the whole app, independent of your selected currency.",
      ur: "یہ پوری ایپ پر لاگو ہوتا ہے، منتخب کردہ کرنسی سے آزاد۔",
      hi: "यह पूरे ऐप पर लागू होता है, चुनी गई मुद्रा से स्वतंत्र।",
      ar: "ينطبق على التطبيق بأكمله، بغض النظر عن العملة المختارة.",
      bn: "পুরো অ্যাপে প্রযোজ্য, নির্বাচিত মুদ্রার থেকে আলাদা।",
      id: "Berlaku di seluruh aplikasi, terlepas dari mata uang yang dipilih.",
      tr: "Seçilen para biriminden bağımsız olarak uygulamanın tamamına uygulanır.",
      fr: "S'applique à toute l'application, indépendamment de la devise sélectionnée.",
    },
    school_field_label: {
      en: "School (madhhab)",
      ur: "مسلک (مذہب)",
      hi: "मसलक (मज़हब)",
      ar: "المذهب",
      bn: "মাযহাব",
      id: "Mazhab",
      tr: "Mezhep",
      fr: "École juridique (madhab)",
    },
    summary_title: {
      en: "Household Zakat summary",
      ur: "گھریلو زکوٰۃ کا خلاصہ",
      hi: "पारिवारिक ज़कात सारांश",
      ar: "ملخص زكاة الأسرة",
      bn: "পারিবারিক যাকাত সারসংক্ষেপ",
      id: "Ringkasan Zakat Keluarga",
      tr: "Hane Zekât Özeti",
      fr: "Récapitulatif de Zakât du foyer",
    },
    summary_sub_a: { en: "School:", ur: "مسلک:", hi: "मसलक:", ar: "المذهب:",
      bn: "মাযহাব:",
      id: "Mazhab:",
      tr: "Mezhep:",
      fr: "École :",
    },
    summary_sub_b: {
      en: "· using your entered rates · calculated as of the Zakat baseline date shown in the header.",
      ur: "· آپ کے درج کردہ نرخوں کے مطابق · ہیڈر میں دکھائی گئی زکوٰۃ کی بنیادی تاریخ کے حساب سے شمار کیا گیا۔",
      hi: "· आपकी दर्ज की गई दरों के अनुसार · हेडर में दिखाई गई ज़कात आधार तिथि के अनुसार गणना की गई।",
      ar: "· باستخدام الأسعار التي أدخلتها · محسوبة حتى تاريخ استحقاق الزكاة الموضح في الأعلى.",
      bn: "· আপনার দেওয়া দরে · হেডারে দেখানো যাকাত বেসলাইন তারিখ অনুযায়ী হিসাব।",
      id: "· menggunakan harga yang Anda masukkan · dihitung per tanggal acuan zakat di header.",
      tr: "· girdiğiniz kurlarla · başlıkta gösterilen zekât başlangıç tarihine göre hesaplanmıştır.",
      fr: "· en utilisant les cours saisis · calculé à la date de référence de la Zakât indiquée dans l'en-tête.",
    },
    card_total_wealth: { en: "Total wealth", ur: "کل مال", hi: "कुल संपत्ति", ar: "إجمالي الثروة",
      bn: "মোট সম্পদ",
      id: "Total harta",
      tr: "Toplam servet",
      fr: "Richesse totale",
    },
    card_zakat_amount: { en: "Zakat amount", ur: "زکوٰۃ کی رقم", hi: "ज़कात राशि", ar: "مبلغ الزكاة",
      bn: "যাকাতের পরিমাণ",
      id: "Jumlah zakat",
      tr: "Zekât miktarı",
      fr: "Montant de la Zakât",
    },
    card_paid: { en: "Paid", ur: "ادا شدہ", hi: "भुगतान किया गया", ar: "المدفوع",
      bn: "প্রদত্ত",
      id: "Dibayar",
      tr: "Ödenen",
      fr: "Versé",
    },
    card_remaining: { en: "Remaining", ur: "باقی", hi: "शेष", ar: "المتبقي",
      bn: "বাকি",
      id: "Sisa",
      tr: "Kalan",
      fr: "Restant",
    },
    family_section_title: {
      en: "Family members & assets",
      ur: "گھر کے افراد اور اثاثے",
      hi: "परिवार के सदस्य और संपत्ति",
      ar: "أفراد الأسرة والممتلكات",
      bn: "পরিবারের সদস্য ও সম্পদ",
      id: "Anggota keluarga & aset",
      tr: "Aile üyeleri ve varlıklar",
      fr: "Membres du foyer et biens",
    },
    family_section_desc: {
      en: "Add each person in your household, then expand their section to record assets and Zakat payments.",
      ur: "گھر کے ہر فرد کو شامل کریں، پھر اس کا سیکشن کھول کر اثاثے اور زکوٰۃ کی ادائیگیاں درج کریں۔",
      hi: "अपने घर के हर सदस्य को जोड़ें, फिर उसका सेक्शन खोलकर संपत्ति और ज़कात भुगतान दर्ज करें।",
      ar: "أضف كل فرد من أفراد أسرتك، ثم افتح قسمه لتسجيل الممتلكات ودفعات الزكاة.",
      bn: "পরিবারের প্রতিটি সদস্য যোগ করুন, তারপর তার বিভাগ খুলে সম্পদ ও যাকাত পেমেন্ট লিখুন।",
      id: "Tambahkan setiap orang di rumah tangga Anda, lalu perluas bagian mereka untuk mencatat aset dan pembayaran zakat.",
      tr: "Hanenizdeki her kişiyi ekleyin, ardından varlıkları ve zekât ödemelerini kaydetmek için bölümlerini genişletin.",
      fr: "Ajoutez chaque membre du foyer, puis développez leur section pour enregistrer les biens et les paiements de Zakât.",
    },
    add_member_btn: {
      en: "Add family member",
      ur: "خاندان کا فرد شامل کریں",
      hi: "परिवार का सदस्य जोड़ें",
      ar: "إضافة فرد من العائلة",
      bn: "পরিবারের সদস্য যোগ করুন",
      id: "Tambah anggota keluarga",
      tr: "Aile üyesi ekle",
      fr: "Ajouter un membre",
    },
    family_empty_state: {
      en: "Save your family name in “Your household” above, then add your first family member.",
      ur: "اوپر “آپ کا گھرانہ” میں اپنے خاندان کا نام محفوظ کریں، پھر اپنا پہلا فرد شامل کریں۔",
      hi: "ऊपर “आपका परिवार” में अपने परिवार का नाम सेव करें, फिर अपना पहला सदस्य जोड़ें।",
      ar: "احفظ اسم عائلتك في “أسرتك” أعلاه، ثم أضف أول فرد من عائلتك.",
      bn: "উপরে \"আপনার পরিবার\"-এ পারিবারিক নাম সেভ করুন, তারপর প্রথম সদস্য যোগ করুন।",
      id: "Simpan nama keluarga di \"Keluarga Anda\" di atas, lalu tambahkan anggota pertama.",
      tr: "Yukarıdaki \"Haneniz\" bölümünde aile adınızı kaydedin, ardından ilk üyeyi ekleyin.",
      fr: "Enregistrez le nom de famille dans « Votre foyer » ci-dessus, puis ajoutez le premier membre.",
    },
    family_empty_no_members: {
      en: "No members yet. Add your first family member above.",
      ur: "ابھی تک کوئی فرد شامل نہیں۔ اوپر اپنا پہلا فرد شامل کریں۔",
      hi: "अभी तक कोई सदस्य नहीं जोड़ा गया। ऊपर अपना पहला सदस्य जोड़ें।",
      ar: "لا يوجد أفراد بعد. أضف أول فرد من عائلتك أعلاه.",
      bn: "এখনো কোনো সদস্য নেই। উপরে প্রথম সদস্য যোগ করুন।",
      id: "Belum ada anggota. Tambahkan anggota pertama di atas.",
      tr: "Henüz üye yok. Yukarıda ilk üyeyi ekleyin.",
      fr: "Aucun membre pour l'instant. Ajoutez le premier membre ci-dessus.",
    },
    toast_add_family_first: {
      en: "Add and save your family name first",
      ur: "پہلے اپنے خاندان کا نام شامل اور محفوظ کریں",
      hi: "पहले अपने परिवार का नाम जोड़ें और सेव करें",
      ar: "أضف اسم عائلتك واحفظه أولاً",
      bn: "আগে পারিবারিক নাম যোগ করুন ও সেভ করুন",
      id: "Tambahkan dan simpan nama keluarga terlebih dahulu",
      tr: "Önce aile adınızı ekleyin ve kaydedin",
      fr: "Ajoutez et enregistrez d'abord le nom de famille",
    },
    school_panel_title: {
      en: "Calculation school (madhhab)",
      ur: "حسابی مسلک (مذہب)",
      hi: "गणना मसलक (मज़हब)",
      ar: "مذهب الحساب",
      bn: "হিসাবের মাযহাব",
      id: "Mazhab perhitungan",
      tr: "Hesaplama mezhebi",
      fr: "École de calcul (madhab)",
    },
    school_panel_sub: {
      en: "Affects nisab basis, jewelry exemption, and debt deduction.",
      ur: "یہ نصاب کی بنیاد، زیورات کی چھوٹ، اور قرض کی کٹوتی پر اثر انداز ہوتا ہے۔",
      hi: "यह निसाब आधार, गहनों की छूट, और कर्ज़ की कटौती को प्रभावित करता है।",
      ar: "يؤثر في أساس النصاب، وإعفاء الحلي، وخصم الديون.",
      bn: "নিসাবের ভিত্তি, গহনার ছাড় ও ঋণ কর্তনে প্রভাব ফেলে।",
      id: "Memengaruhi dasar nisab, pembebasan perhiasan, dan pengurangan utang.",
      tr: "Nisap esasını, takı muafiyetini ve borç kesintisini etkiler.",
      fr: "Affecte la base du nisab, l'exemption des bijoux et la déduction des dettes.",
    },
    toast_school_updated: {
      en: "School updated",
      ur: "مسلک اپ ڈیٹ ہو گیا",
      hi: "मसलक अपडेट हो गया",
      ar: "تم تحديث المذهب",
      bn: "মাযহাব আপডেট হয়েছে",
      id: "Mazhab diperbarui",
      tr: "Mezhep güncellendi",
      fr: "École mise à jour",
    },
  };

  let lang = "en";
  try {
    const savedLang = localStorage.getItem(LS_KEY);
    if (savedLang && LANG_LABELS[savedLang]) lang = savedLang;
  } catch (e) { /* storage unavailable */ }

  function getLang() { return lang; }

  function setLang(code) {
    lang = LANG_LABELS[code] ? code : "en";
    try { localStorage.setItem(LS_KEY, lang); } catch (e) { /* ignore */ }
  }

  function t(key) {
    const entry = S[key];
    if (!entry) return "";
    return entry[lang] || entry.en || "";
  }

  // The site's supported languages, independent of currency.
  function availableLangs() {
    return Object.keys(LANG_LABELS);
  }

  function effectiveLang() {
    return availableLangs().indexOf(lang) >= 0 ? lang : "en";
  }

  function applyDirection(node, code) {
    if (RTL_LANGS.has(code)) { node.setAttribute("dir", "rtl"); node.setAttribute("lang", code); }
    else { node.removeAttribute("dir"); node.setAttribute("lang", code); }
  }

  // Bind a node to a help key so refresh() can re-translate it in place.
  function bind(node, key) {
    node.dataset.helpKey = key;
    const code = effectiveLang();
    const entry = S[key];
    node.textContent = entry ? (entry[code] || entry.en || "") : "";
    applyDirection(node, code);
    return node;
  }

  // Re-translate every bound node currently in the document.
  function refresh(root) {
    const scope = root || document;
    const code = effectiveLang();
    scope.querySelectorAll("[data-help-key]").forEach((node) => {
      const entry = S[node.dataset.helpKey];
      if (!entry) return;
      node.textContent = entry[code] || entry.en || "";
      applyDirection(node, code);
    });
  }

  global.ZKHelp = {
    LANG_LABELS, availableLangs, getLang, setLang, effectiveLang, t, bind, refresh, applyDirection,
  };
})(window);
